/*Subsequences of String
Link - https://www.naukri.com/code360/problems/subsequences-of-string_985087
Moderate
Problem statement
You are given a string 'STR' containing lowercase English letters from a to z inclusive. Your task is to find all non-empty possible subsequences of 'STR'.

A Subsequence of a string is the one which is generated by deleting 0 or more letters from the string and keeping the rest of the letters in the same order.
Detailed explanation ( Input/output format, Notes, Images )
Constraints:
1 <= T <= 10 
1 <=  |STR| <= 16

Where |STR| represents the length of the string 'STR'.

Time Limit: 1 sec
Sample Input 1:
1 
abc
Sample Output 1:
a ab abc ac b bc c
Explanation of sample input 1:
All possible subsequences of abc are :  
“a” , “b” , “c” , “ab” , “bc” , “ac”, “abc”
Sample Input 2:
1
bbb
Sample Output 2:
b b b bb bb bb bbb

*/
#include<bits/stdc++.h>
using namespace std;

void solve(string str,vector<string>& ans,string s,int idx){
	if (idx>=str.size()){
		if (s.size()>=1){
			ans.push_back(s);
		}
		return;
	}
	solve(str,ans,s,idx+1);
	s+=str[idx];
	solve(str,ans,s,idx+1);
}
vector<string> subsequences(string str){
	
	int idx =0;
	string s = "";
	vector<string>ans;
	solve(str,ans,s,idx);
    sort(ans.begin(),ans.end());
	return ans;
	
}
int main() {
    int t;
    cin >> t;
    cin.ignore();
    while (t--) {
        string s1;
        cin>> s1;
        
        vector<string>ans = subsequences(s1);
        for (auto i :ans)
            cout << i << " ";
        cout <<endl<< "~" << endl;
    }
    return 0;
}